# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: leak

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
         ref: ${{ github.head_ref }}
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.36.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
